services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - backend
  mongodb:
    attach: false
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - backend
  redis:
    attach: false
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend:

