worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    server {
        listen 80;
        # Serve static files
        # location / {
        #     root /usr/share/nginx/html;
        #     index index.html;
        # }

        # Reverse proxy to backend service on port 3000
        location /user {
            rewrite ^/user(.*)$ $1 break;
            proxy_pass http://user-svc:8080/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
